"""Offline training for the claim-severity model.

Trains a Logistic Regression on 20,000 synthetic claims to predict the
probability that a claim becomes HIGH SEVERITY (top-quartile cost), then
exports the fitted scaler + coefficients to `api/_model.py` as plain data.

Why export instead of shipping the pickle?
- The serverless runtime needs zero heavy dependencies (no sklearn/numpy),
  keeping cold starts fast and the bundle far under platform size limits.
- A coefficients-as-code artefact is diffable, reviewable and auditable —
  you can see in the pull request exactly how the model changed.
This is the same train-heavy / serve-light pattern used for edge deployment.
"""

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

RNG = np.random.default_rng(21)
N = 20_000

FEATURES = ["log_claim_amount", "report_delay_days", "policy_tenure_months",
            "prior_claims_count", "injury_mentioned", "third_party_involved",
            "attorney_mentioned", "incident_is_liability_or_medical"]


def generate() -> pd.DataFrame:
    claim_amount = RNG.lognormal(10.2, 1.1, N)
    injury = RNG.uniform(size=N) < 0.22
    third_party = RNG.uniform(size=N) < 0.30
    attorney = (RNG.uniform(size=N) < 0.06) | (injury & (RNG.uniform(size=N) < 0.25))
    liability_medical = RNG.uniform(size=N) < 0.18
    delay = RNG.exponential(4, N).clip(0, 90)
    tenure = RNG.uniform(1, 120, N)
    priors = RNG.poisson(0.4, N).clip(0, 6)

    # Hidden severity driver: injuries, attorneys and liability claims
    # escalate cost; the model must recover this from the features.
    latent = (
        0.9 * np.log(claim_amount / 20000)
        + 1.6 * injury + 0.8 * attorney + 0.7 * liability_medical
        + 0.4 * third_party + 0.01 * delay
        + RNG.normal(0, 0.8, N)
    )
    high_severity = (latent > np.quantile(latent, 0.75)).astype(int)

    return pd.DataFrame({
        "log_claim_amount": np.log(claim_amount),
        "report_delay_days": delay,
        "policy_tenure_months": tenure,
        "prior_claims_count": priors,
        "injury_mentioned": injury.astype(int),
        "third_party_involved": third_party.astype(int),
        "attorney_mentioned": attorney.astype(int),
        "incident_is_liability_or_medical": liability_medical.astype(int),
        "high_severity": high_severity,
    })


def main():
    df = generate()
    X, y = df[FEATURES], df["high_severity"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

    scaler = StandardScaler().fit(X_train)
    model = LogisticRegression(max_iter=1000).fit(scaler.transform(X_train), y_train)
    auc = roc_auc_score(y_test, model.predict_proba(scaler.transform(X_test))[:, 1])
    print(f"Severity model ROC-AUC: {auc:.3f}")

    artefact = {
        "features": FEATURES,
        "means": scaler.mean_.round(6).tolist(),
        "stds": scaler.scale_.round(6).tolist(),
        "coefficients": model.coef_[0].round(6).tolist(),
        "intercept": round(float(model.intercept_[0]), 6),
        "test_roc_auc": round(float(auc), 3),
    }
    out = Path(__file__).resolve().parents[1] / "api" / "_model.py"
    out.write_text(
        '"""GENERATED by training/train_severity.py — do not edit by hand."""\n\n'
        f"MODEL = {artefact!r}\n",
        encoding="utf-8",
    )
    print(f"Exported model artefact to {out}")


if __name__ == "__main__":
    main()
